name: Hello World Matrix with Params

on:
  workflow_call:   # Make sure it's exactly like this and directly under 'on'

    inputs:
      greeting:
        description: "The greeting message to print"
        required: true
        type: string
      languages:
        description: "List of languages to run the Hello World program"
        required: false
        type: [string]
        default: [python, javascript, shell, go]

jobs:
  hello_world:
    name: Run Hello World
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ inputs.languages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hello World
        run: |
          echo "${{ inputs.greeting }} from ${{ matrix.language }}!"
