name: Hello World Matrix Params

on:
  workflow_call:
    inputs:
      greeting:
        description: "The greeting message to print"
        required: true
        type: string
      languages:
        description: "List of languages to run the Hello World program"
        required: false
        type: array
        default: [python, javascript, shell, go]

jobs:
  hello_world:
    name: Run Hello World
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ inputs.languages }}
        include:
          - language: python
            file: common/hello-world.py
            command: python3
          - language: javascript
            file: common/hello-world.ts
            command: ts-node
          - language: shell
            file: common/hello-world.sh
            command: bash
          - language: go
            file: common/hello-world.go
            command: go run
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if JavaScript)
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Set up Go (if Go)
        if: matrix.language == 'go'
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Run Hello World
        run: |
          echo "${{ inputs.greeting }} from ${{ matrix.language }}!"
          ${{ matrix.command }} ${{ matrix.file }}
